=== Sector-Echo-13-Team/Echo-13/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-04/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": [ "null", "string" ],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"COLONIAL MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CMM-BARD"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 2
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		}
	},

	"required": ["map_name", "map_path"]
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_shepherd.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Shepherd-Class Space Monastery",
	"map_short_name": "Shepherd-class",
	"map_path": "_maps/shuttles/shiptest/independent_shepherd.dmm",
	"prefix": "ISV",
	"namelists": [
		"MYTHOLOGICAL"
	],
	"job_slots": {
		"Chaplain": 1,
		"Curator": 1,
		"Station Engineer": 1,
		"Acolyte": {
			"outfit": "/datum/outfit/job/assistant/intern",
			"slots": 6
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_box.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Box-class Hospital Ship",
	"map_short_name": "Box-class",
	"map_path": "_maps/shuttles/shiptest/independent_box.dmm",
	"namelists": [
		"GENERAL",
		"SPACE",
		"NATURAL"
	],
	"prefix": "ISV",
	"job_slots": {
		"Chief Medical Officer": 1,
		"Medical Doctor": {
			"outfit": "/datum/outfit/job/doctor",
			"slots": 3
		},
		"Paramedic": 2,
		"Assistant": 3
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_rigger.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Riggs-class Sloop",
	"prefix": "SV",
	"namelists": [
		"GENERAL",
		"SPACE",
		"NATURAL",
		"NATURAL_AGGRESSIVE"
	],
	"map_short_name": "Riggs-class",
	"map_path": "_maps/shuttles/shiptest/independent_rigger.dmm",
	"roundstart": true,
	"limit": 2,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/western",
			"officer": true,
			"slots": 1
		},
		"First Mate": {
			"outfit": "/datum/outfit/job/head_of_personnel/western",
			"officer": true,
			"slots": 1
		},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/doctor",
			"slots": 1
		},
		"Machinist's Mate": {
			"outfit": "/datum/outfit/job/engineer",
			"slots": 2
		},
		"Asteroid Miner": {
			"outfit": "/datum/outfit/job/miner/hazard",
			"slots": 2
		},
		"Mech Technician": {
			"outfit": "/datum/outfit/job/roboticist/technician",
			"slots": 1
		},
		"Security Detail": {
			"outfit": "/datum/outfit/job/security/western",
			"slots": 1
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 4
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/nanotrasen_skipper.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Skipper-class Heavy Cruiser",
	"map_short_name": "Skipper-class",
	"prefix": "NTSV",
	"namelists": [
		"NANOTRASEN",
		"SPACE",
		"MYTHOLOGICAL",
		"WEAPONS",
		"MERCANTILE"
	],
	"map_path": "_maps/shuttles/shiptest/nanotrasen_skipper.dmm",
	"roundstart": true,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/nt",
			"officer": true,
			"slots": 1
		},
		"First Officer": {
			"outfit": "/datum/outfit/job/head_of_personnel/nt",
			"officer": true,
			"slots": 1
		},
		"Internal Affairs Agent": {
			"outfit": "/datum/outfit/job/lawyer/corporaterepresentative",
			"slots" : 1
		},
		"Medical Doctor": 1,
		"Engineer": {
			"outfit": "/datum/outfit/job/engineer/nt",
			"slots": 3
		},
		"Shaft Miner": 2,
		"Security Officer": {
			"outfit": "/datum/outfit/job/security/nanotrasen",
			"slots": 1
		},
		"Assistant": 3
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_masinyane.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Masinyane-Class Personal Shuttle",
	"map_short_name": "Masinyane-Class",
	"prefix": "ISV",
	"namelists": [
		"MYTHOLOGICAL",
		"NATURAL"
	],
	"map_path": "_maps/shuttles/shiptest/independent_masinyane.dmm",
	"job_slots": {
		"Private Ship Owner": {
			"outfit": "/datum/outfit/job/captain/independent/owner",
			"officer": true,
			"slots": 1
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/engineer/independent/ship_engineer",
			"slots": 1
		},
		"Crewmate": {
			"outfit": "/datum/outfit/job/assistant/independent/crewmatefancy",
			"slots": 1
		}
	}
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/inteq_talos.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Talos-Class Command Clipper",
	"prefix": "IRMV",
	"namelists": ["MYTHOLOGICAL", "BEASTS", "NATURAL_AGGRESSIVE"],
	"map_short_name": "Talos-class",
	"map_path": "_maps/shuttles/shiptest/inteq_talos.dmm",
	"limit": 1,
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/captain/inteq",
			"officer": true,
			"slots": 1
		},
		"Master At Arms": {
			"outfit": "/datum/outfit/job/warden/inteq",
			"officer": true,
			"slots": 1
		},
		"Artificer Class II": {
			"outfit": "/datum/outfit/job/ce/inteq",
			"officer": true,
			"slots": 1
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/engineer/inteq",
			"slots": 3
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/paramedic/inteq",
			"slots": 1
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/security/inteq",
			"slots": 1
		},
		"Recruit": {
			"outfit": "/datum/outfit/job/assistant/inteq",
			"slots": 7
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/syndicate_luxembourg.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"prefix": "SSV",
	"namelists": ["DONK", "MERCANTILE", "SPACE"],
	"map_name": "Luxembourg-class Delivery Vessel",
	"map_short_name": "Luxembourg-class",
	"map_path": "_maps/shuttles/shiptest/syndicate_luxembourg.dmm",
	"limit": 1,
	"job_slots": {
		"Manager": {
			"outfit": "/datum/outfit/job/quartermaster/donk",
			"slots": 1
		},
		"Customer Service Representative": {
			"outfit": "/datum/outfit/job/cargo_tech/donk",
			"slots": 5
		},
		"Food and Beverage Specialist": {
			"outfit": "/datum/outfit/job/bartender/syndicate",
			"slots": 1
		},
		"GEC Contracted Engineer": {
			"outfit": "/datum/outfit/job/engineer/gec",
			"slots": 1
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/pirate_ember.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Ember-Class Pirate Raider",
	"prefix": "ISV",
	"namelists": [
		"PIRATES",
		"BRITISH_NAVY"
	],
	"map_short_name": "Ember-class",
	"map_path": "_maps/shuttles/shiptest/pirate_ember.dmm",
	"limit": 1,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/frontiersmen",
			"officer": true,
			"slots": 1
		},
		"Bridge Officer": {
			"outfit": "/datum/outfit/job/head_of_personnel/frontiersmen",
			"officer": true,
			"slots": 2
		},
		"Master At Arms": {
			"outfit": "/datum/outfit/job/hos/frontiersmen",
			"officer": true,
			"slots": 1
		},
		"Head Carpenter" :{
			"outfit": "/datum/outfit/job/ce/frontiersmen",
			"officer": true,
			"slots": 1
		},
		"Cargo Tech": {
			"outfit": "/datum/outfit/job/cargo_tech/frontiersmen",
			"slots": 2
		},
		"Surgeon": {
			"outfit": "/datum/outfit/job/doctor/frontiersmen",
			"slots": 1
		},
		"Carpenter": {
			"outfit": "/datum/outfit/job/engineer/independent/frontiersmen",
			"slots": 2
		},
		"Atmospheric Technician": {
			"outfit": "/datum/outfit/job/atmos/frontiersmen",
			"slots": 1
		},
		"Steward": {
			"outfit": "/datum/outfit/job/cook/frontiersmen",
			"slots": 1
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/assistant/frontiersmen",
			"slots": 3
		},
		"Buccaneer": {
			"outfit": "/datum/outfit/job/security/Frontiersmen",
			"slots": 3
		}
	},
	"enabled": false
}
