=== Sector-Echo-13-Team/Echo-13/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-04/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": [ "null", "string" ],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"COLONIAL MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CMM-BARD"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 2
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		}
	},

	"required": ["map_name", "map_path"]
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/deserter_rigger.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Rigoureux(D)-class Auxiliary Cutter",
	"map_short_name": "Rigoureux(D)-class",
	"map_path": "_maps/shuttles/shiptest/independent_rigger_c.dmm",
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/solgov/rebel",
			"officer": true,
			"slots": 1
		},
		"Executive Officer": {
			"outfit": "/datum/outfit/job/head_of_personnel/solgov/rebel",
			"officer": true,
			"slots": 1
		},
		"Signal Officer": {
			"outfit": "/datum/outfit/job/solgov/rebel",
			"officer": true,
			"slots": 1
		},
		"Naval Surgeon": {
			"outfit": "/datum/outfit/job/doctor/solgov/rebel",
			"slots": 1
		},
		"Machinist": {
			"outfit": "/datum/outfit/job/engineer/solgov/rebel",
			"slots": 2
		},
		"Field Engineer": {
			"outfit": "/datum/outfit/job/miner/solgov/rebel",
			"slots": 2
		},
		"Cook": 1,
		"Boarding Specialist": {
			"outfit": "/datum/outfit/job/security/solgov/rebel",
			"slots": 3
		},
		"Sailor": {
			"outfit": "/datum/outfit/job/assistant/solgov/rebel",
			"slots": 4
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/nanotrasen_delta.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Delta-class Frigate",
	"prefix": "NTSV",
	"namelists": [
		"GENERAL",
		"SPACE",
		"BRITISH_NAVY",
		"MERCANTILE",
		"NANOTRASEN"
	],
	"map_short_name": "Delta-class",
	"map_path": "_maps/shuttles/shiptest/nanotrasen_delta.dmm",
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/nt",
			"officer": true,
			"slots": 1
		},
		"Roboticist": 2,
		"Engineer": {
			"outfit": "/datum/outfit/job/engineer/nt",
			"slots": 1
		},
		"Assistant": 3
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/solgov_cricket.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Cricket-Class Solgov Intel Scout",
	"map_short_name": "Solgov Cricket",
	"map_path": "_maps/shuttles/shiptest/solgov_cricket.dmm",
	"job_slots": {
		"Captain": 1,
		"SolGov Representative": 1,
		"Chemist": 1,
		"Station Engineer": 2,
		"Shaft Miner": 2,
		"Cargo Technician": 1,
		"Security Officer": 1,
		"Cook": 1,
		"Assistant": 3
	},
	"enabled": false
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_bubble.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Bubble-class Colonial Ship",
	"map_short_name": "Bubble-class",
	"map_path": "_maps/shuttles/shiptest/independent_bubble.dmm",
	"limit": 1,
	"job_slots": {
		"Captain": 1,
		"Scientist": 1,
		"Station Engineer": 1,
		"Shaft Miner": 1,
		"Assistant": 3
	},
	"enabled": false
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_solar.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Solar-class Research Vessel",
	"map_short_name": "Solar-class",
	"map_path": "_maps/shuttles/shiptest/independent_solar.dmm",
	"prefix": "ISV",
	"namelists": ["SPACE", "GENERAL"],
	"job_slots": {
		"Captain": 1,
		"Head of Personnel": 1,
		"Medical Doctor": 2,
		"Station Engineer": 3,
		"Shaft Miner": 2,
		"Cargo Technician": 2,
		"Security Officer": 1,
		"Assistant": 5
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/inteq_colossus.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Colossus-Class Armored Frigate",
	"prefix": "IRMV",
	"namelists": ["MYTHOLOGICAL", "BEASTS", "NATURAL_AGGRESSIVE"],
	"map_short_name": "Colossus-class",
	"map_path": "_maps/shuttles/shiptest/inteq_colossus.dmm",
	"limit": 1,
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/captain/inteq/naked",
			"officer": true,
			"slots": 1
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/engineer/inteq",
			"slots": 1
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/paramedic/inteq",
			"slots": 1
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/security/inteq",
			"slots": 3
		},
		"Recruit": {
			"outfit": "/datum/outfit/job/assistant/inteq",
			"slots": 5
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_litieguai.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Li Tieguai-class Rescue Ship",
	"map_short_name": "Li Tieguai-class",
	"map_path": "_maps/shuttles/shiptest/independent_litieguai.dmm",
	"namelists": [
		"SPACE",
		"BEASTS",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Captain": 1,
		"Chief Medical Officer": {
			"outfit": "/datum/outfit/job/cmo/medicaldirector",
			"officer": true,
			"slots": 1
		},
		"Trauma Team Technician": {
			"outfit": "/datum/outfit/job/paramedic/traumateam",
			"slots": 3
		},
		"Medical Intern": {
			"outfit": "/datum/outfit/job/doctor/juniordoctor",
			"slots": 3
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/pirate_libertatia.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Libertatia-class Hauler",
	"map_short_name": "Libertatia-class",
	"map_path": "_maps/shuttles/shiptest/pirate_libertatia.dmm",
	"prefix": "ISV",
	"namelists": ["PIRATES", "NATURAL_AGGRESSIVE"],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/pirate",
			"officer": true,
			"slots": 1
		},
		"First Mate": {
			"outfit": "/datum/outfit/job/head_of_personnel/pirate",
			"officer": true,
			"slots": 1
		},
		"Buccaneer": {
			"outfit": "/datum/outfit/job/security/pirate",
			"slots": 2
		},
		"Motorman": {
			"outfit": "/datum/outfit/job/engineer/pirate",
			"slots": 1
		},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/doctor/pirate",
			"slots": 1
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/assistant/pirate",
			"slots": 4
		}
	},
	"enabled": false
}
