=== Sector-Echo-13-Team/Echo-13/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-04/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": [ "null", "string" ],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"COLONIAL MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CMM-BARD"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 2
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		}
	},

	"required": ["map_name", "map_path"]
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_caravan.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Caravan-class Modular ship",
	"map_short_name": "Caravan-class",
	"map_path": "_maps/shuttles/shiptest/independent_caravan.dmm",
	"prefix": "ISV",
	"namelists": [
		"GENERAL",
		"SPACE",
		"MYTHOLOGICAL",
		"NATURAL"
	],
	"roundstart": true,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/western",
			"officer": true,
			"slots": 1
		},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/doctor",
			"slots": 1
		},
		"Engine Technician": {
			"outfit": "/datum/outfit/job/atmos",
			"slots": 1
		},
		"Asteroid Miner": {
			"outfit": "/datum/outfit/job/miner/hazard",
			"slots": 1
		},
		"Fauna Researcher": {
			"outfit": "/datum/outfit/job/scientist",
			"slots": 1
		},
		"Assistant": 1
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_scav.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Scav-class Drifter",
	"map_short_name": "Scav-class",
	"prefix": "ISV",
	"namelists": [
		"NATURAL",
		"SPACE"
	],
	"map_path": "_maps/shuttles/shiptest/independent_scav.dmm",
	"roundstart": true,
	"job_slots": {
		"Salvage Leader": {
			"outfit": "/datum/outfit/job/captain",
			"officer": true,
			"slots": 1
		},
		"Salvage Technician": {
			"outfit": "/datum/outfit/job/engineer/maintenancetechnician",
			"slots": 1
		},
		"Salvage Doctor": {
			"outfit": "/datum/outfit/job/doctor/juniordoctor",
			"slots": 1
		},
		"Salvagee": {
			"outfit": "/datum/outfit/job/assistant/engineeringspecialist",
			"slots": 1
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/syndicate_twinkleshine.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"prefix": "SSV",
	"namelists": ["GENERAL", "SPACE", "HISTORICAL"],
	"map_name": "Twinkleshine-class Battle Cruiser",
	"map_short_name": "Twinkleshine-class",
	"map_path": "_maps/shuttles/shiptest/syndicate_twinkleshine.dmm",
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/syndicate/sbc",
			"officer": true,
			"slots": 1
		},
		"Lieutenant": {
			"outfit": "/datum/outfit/job/warden/syndicate/sbc",
			"officer": true,
			"slots": 1
		},
		"Medic": {
			"outfit": "/datum/outfit/job/brig_phys/syndicate/sbc",
			"slots": 2
		},
		"Engineer": {
			"outfit": "/datum/outfit/job/engineer/syndicate/sbc",
			"slots": 2
		},
		"Operative": {
			"outfit": "/datum/outfit/job/security/syndicate/sbc",
			"slots": 5
		},
		"Bartender": {
			"outfit": "/datum/outfit/job/bartender/syndicate/sbc",
			"slots": 1
		},
		"Miner": {
			"outfit": "/datum/outfit/job/miner/syndicate/sbc",
			"slots": 1
		},
		"Deck Assistant": {
			"outfit": "/datum/outfit/job/assistant/syndicate/sbc",
			"slots": 2
		}
	},
	"enabled" : false
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/nanotrasen_mimir.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"prefix": "NTSV",
	"namelists": ["GENERAL", "NATURAL_AGGRESSIVE", "BEASTS"],
	"map_name": "Mimir-Class Rehabillitation Vessel",
	"map_short_name": "Mimir-Class",
	"map_path": "_maps/shuttles/shiptest/nanotrasen_mimir.dmm",
	"limit": 1,
	"job_slots": {
		"Warden": {
			"outfit": "/datum/outfit/job/warden",
			"officer": true,
			"slots": 1
		},
		"Facility Security Officer": {
			"outfit": "/datum/outfit/job/security",
			"slots": 2
		},
		"Facility Physician": {
			"outfit": "/datum/outfit/job/brig_phys",
			"slots": 1
		},
		"Patient": {
			"outfit": "/datum/outfit/job/prisoner",
			"slots": 2
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_lagoon.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Lagoon-class Cruise Ship",
	"prefix": "ISV",
	"namelists": [
		"CRUISE"
	],
	"map_short_name": "Lagoon-class",
	"map_path": "_maps/shuttles/shiptest/independent_lagoon.dmm",
	"job_slots": {
		"Captain": 1,
		"Cruise Director": {
			"outfit": "/datum/outfit/job/head_of_personnel",
			"slots": 1
		},
		"Security Officer": 2,
		"Medical Doctor": 1,
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/atmos",
			"slots": 1
		},
		"Bartender": 1,
		"Cook": 1,
		"Botanist": 1,
		"Curator": 1,
		"Chaplain": 1,
		"Janitor": 1,
		"Passenger": {
			"outfit": "/datum/outfit/job/assistant/corporate",
			"slots": 10
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_arrowhead.json
{
	"$schema": "https://raw.githubusercontent.com/Sector-Echo-13-Team/Echotest/master/_maps/ship_config_schema.json",
	"map_name": "Arrowhead-class Long Range Scoutship",
	"prefix": "ISV",
	"namelists": [
		"GENERAL",
		"SPACE",
		"MYTHOLOGICAL"
	],
	"map_short_name": "Arrowhead-class",
	"map_path": "_maps/shuttles/shiptest/independent_arrowhead.dmm",
	"roundstart": true,
	"job_slots": {
		"Captain": 1,
		"Medical Doctor": 1,
		"Botanist": 1,
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/engineer",
			"slots": 1
		},
		"Field Surveyor": {
			"outfit": "/datum/outfit/job/miner/hazard",
			"slots": 1
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 2
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/minutemen_cepheus.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Cepheus-Class Mech Carrier",
	"prefix": "CMSV",
	"namelists": ["BRITISH_NAVY", "MYTHOLOGICAL"],
	"map_short_name": "Cepheus-class",
	"map_path": "_maps/shuttles/shiptest/minutemen_cepheus.dmm",
	"limit": 1,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/minutemen",
			"officer": true,
			"slots": 1
		},
		"Mechanic": {
			"outfit": "/datum/outfit/job/engineer/minutemen",
			"slots": 1
		},
		"Minuteman": {
			"outfit": "/datum/outfit/job/security/minutemen",
			"slots": 2
		},
		"Mech Pilot" :{
			"outfit": "/datum/outfit/job/security/minutemen/mechpilot",
			"slots": 2
		},
		"Roboticist": {
			"outfit": "/datum/outfit/job/roboticist/technician/minutemen",
			"slots": 1
		},
		"Cadet": {
			"outfit": "/datum/outfit/job/assistant/minutemen",
			"slots": 3
		}
	},
	"enabled": true
}

=== Sector-Echo-13-Team/Echo-13/_maps/configs/independent_meta.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Meta-class Freighter",
	"prefix": "ISV",
	"map_short_name": "Meta-class",
	"namelists": [
		"GENERAL",
		"SPACE",
		"HISTORICAL"
	],
	"map_path": "_maps/shuttles/shiptest/independent_meta.dmm",
	"job_slots": {
		"Captain": 1,
		"Quartermaster": 1,
		"Medical Doctor": {
			"outfit": "/datum/outfit/job/doctor",
			"slots": 1
		},
		"Station Engineer": 1,
		"Shaft Miner": 1,
		"Assistant": 3
	},
	"enabled": true
}
